"""Cocotb testbench for RMSNorm unit.

Tests the RMSNorm hardware against golden samples generated by PyTorch.
Uses a simple FSM-driven approach: feed weight, then feed input vectors.
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import cocotb
from cocotb.triggers import Timer, RisingEdge, ClockCycles
from cocotb.clock import Clock

WIDTH = 768
NUM_VECTORS = 10


def read_hex_file(filepath):
    """Read hex file and return list of integers."""
    values = []
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if line:
                values.append(int(line, 16))
    return values


async def reset_dut(dut):
    """Reset the DUT."""
    dut.rst_n.value = 0
    dut.valid_in.value = 0
    dut.data_in.value = 0
    dut.weight_valid.value = 0
    dut.weight_in.value = 0
    await ClockCycles(dut.clk, 5)
    dut.rst_n.value = 1
    await ClockCycles(dut.clk, 2)


async def load_weight(dut, weight_data):
    """Load weight vector into the DUT."""
    dut._log.info(f"Loading weight vector ({len(weight_data)} elements)")
    
    for i, w in enumerate(weight_data):
        dut.weight_valid.value = 1
        dut.weight_in.value = w
        await RisingEdge(dut.clk)
    
    dut.weight_valid.value = 0
    dut.weight_in.value = 0
    await RisingEdge(dut.clk)
    
    # Wait for weight loading FSM to complete
    await ClockCycles(dut.clk, 10)
    dut._log.info("Weight loaded")


async def feed_input(dut, input_data):
    """Feed input vector to the DUT."""
    dut._log.info(f"Feeding input vector ({len(input_data)} elements)")
    
    for i, x in enumerate(input_data):
        dut.valid_in.value = 1
        dut.data_in.value = x
        await RisingEdge(dut.clk)
    
    dut.valid_in.value = 0
    dut.data_in.value = 0
    dut._log.info("Input fed")


async def wait_for_output(dut, expected_count, max_cycles=200000):
    # The pipelined fp_unit's iterative divider serializes the per-element
    # DIV/MUL (17 + 4 cycles), so a full vector takes ~25 x WIDTH cycles.
    """Wait for output values and collect them."""
    output_collected = []
    
    for cycle in range(max_cycles):
        await RisingEdge(dut.clk)
        
        if int(dut.valid_out.value) == 1:
            output_collected.append(int(dut.data_out.value))
            
            if len(output_collected) >= expected_count:
                break
    
    return output_collected


@cocotb.test()
async def test_rmsnorm(dut):
    """Main test: process multiple vectors against golden samples."""
    # Start clock (100 MHz)
    clock = Clock(dut.clk, 10, units="ns")
    cocotb.start_soon(clock.start())
    
    # Reset
    await reset_dut(dut)
    
    # Load weight
    script_dir = Path(__file__).parent
    weight_data = read_hex_file(script_dir / "weight.hex")
    await load_weight(dut, weight_data)
    
    # Process test vectors
    results = []
    for i in range(NUM_VECTORS):
        dut._log.info(f"\n=== Vector {i} ===")
        
        # Read golden data
        input_data = read_hex_file(script_dir / f"input_{i}.hex")
        expected_output = read_hex_file(script_dir / f"output_{i}.hex")
        
        # Feed input
        await feed_input(dut, input_data)
        
        # Wait for output
        output_collected = await wait_for_output(dut, WIDTH)
        
        if len(output_collected) < WIDTH:
            dut._log.error(f"Vector {i}: Only collected {len(output_collected)} outputs, expected {WIDTH}")
            results.append(False)
            continue
        
        # Compare with expected output
        mismatches = 0
        first_mismatches = []
        for j, (got, exp) in enumerate(zip(output_collected, expected_output)):
            if got != exp:
                mismatches += 1
                if len(first_mismatches) < 5:
                    first_mismatches.append((j, got, exp))
        
        if mismatches == 0:
            dut._log.info(f"Vector {i}: PASS")
            results.append(True)
        else:
            dut._log.error(f"Vector {i}: FAIL ({mismatches} mismatches)")
            for idx, got, exp in first_mismatches:
                dut._log.error(f"  [{idx}]: got 0x{got:04x}, expected 0x{exp:04x}")
            results.append(False)
        
        # Reset for next vector
        await reset_dut(dut)
        await load_weight(dut, weight_data)
    
    # Summary
    passed = sum(results)
    total = len(results)
    dut._log.info(f"\n{'='*50}")
    dut._log.info(f"Test Summary: {passed}/{total} vectors passed")
    
    if passed == total:
        dut._log.info("ALL TESTS PASSED!")
    else:
        dut._log.error("SOME TESTS FAILED!")
        assert False, f"{total - passed} vectors failed"
