SIM ?= verilator
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = sigmoid_unit.sv
TOPLEVEL = sigmoid_unit
MODULE = tb_sigmoid_unit
COMPILE_ARGS = -Wall
include $(shell cocotb-config --makefiles)/Makefile.sim
